spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=todolist_db;encrypt=false
    username: sa
    password: "123"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
